<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>svo_img_align</name>
  <description>
    SVO image align module used for direct image alignment
  </description>
  <version>0.0.1</version>
  <license>GPLv3</license>

  <author>Christian Forster</author>
  <author>Manuel Werlberger</author>
  <author>Michael Gassner</author>
  <maintainer email="forster@ifi.uzh.ch">Christian Forster</maintainer>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>svo_cmake</depend>
  <depend>svo_common</depend>
  <depend>svo_direct</depend>
  <depend>vikit_solver</depend>
  <depend>vikit_ros</depend>
  <depend>eigen_checks</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
